### PR TITLE
Fixes for DM-3898: compiler warnings with clang

### PR DESCRIPTION
**Pull request by fritzm**
Address some warnings generated by clang

### CODE REVIEW

**Comment by abh3** [comment]
Hi Fritz,

The update to src/XrdSsi/XrdSsiResponder.hh introduces a fatal error and cannot be accepted. Setting metadata does not trigger a call to ProcessResponse(). In fact, it cannot do that at all. The call to ProcessResponse() is triggered by calling one of the SetResponse() methods. Could you resubmit the pull request omitting the responder path.

Andy

**Comment by abh3** [comment]
One more thing, the correct fix it to simply add
return wasPosted;
after the UnLock().

**Comment by fritzm** [comment]
Ah, I see, thanks...  I’ll resubmit.

**Comment by fritzm** [comment]
Re-opening -- revised changes will be pushed here shortly...

**Comment by fritzm** [comment]
Okay, revised, thanks!  (FYI, once these changes pass muster, I'll push them around in our lsst xrootd repo, then generate a pull request to the official xrootd repo.  So there's no need to apply them in parallel in the official repo before then.)

**Pull request merged**
